"use client";
import React, { useState } from 'react';
import { useAppStore } from '@/store/appStore';
import SeverityBadge from '@/components/ui/SeverityBadge';

export default function ReportsPage() {
  const { incidents } = useAppStore();
  const [selectedInc, setSelectedInc] = useState(incidents[0]?.id);

  const incident = incidents.find(i => i.id === selectedInc);

  return (
    <div className="flex flex-col gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500 min-h-full">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <i className="bx bx-file text-[#22D3EE]"></i>
            Reports
          </h2>
          <p className="text-[#A1A1AA] text-sm mt-1">Generate and view final incident reports.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="card p-4">
          <h3 className="text-sm font-bold text-[#A1A1AA] uppercase tracking-wider mb-4">Select Incident</h3>
          <div className="flex flex-col gap-2">
            {incidents.map(inc => (
              <button 
                key={inc.id}
                onClick={() => setSelectedInc(inc.id)}
                className={`text-left px-4 py-3 rounded-xl transition-colors ${selectedInc === inc.id ? 'bg-[#ffffff14] border border-[#ffffff1a]' : 'hover:bg-[#ffffff05] border border-transparent'}`}
              >
                <div className="flex justify-between items-start mb-1">
                  <span className="text-xs font-bold text-[#A1A1AA]">{inc.id}</span>
                  <SeverityBadge severity={inc.severity} />
                </div>
                <p className="text-sm text-white truncate">{inc.title}</p>
              </button>
            ))}
          </div>
        </div>

        <div className="lg:col-span-3">
          {incident ? (
            <div className="card p-0 flex flex-col h-full bg-[#0A0A0A] border border-[#ffffff14]">
              {/* Report Toolbar */}
              <div className="p-4 border-b border-[#ffffff14] flex justify-between items-center bg-[#ffffff05]">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded bg-[#C871DA]/20 text-[#C871DA] flex items-center justify-center">
                    <i className="bx bx-file text-xl"></i>
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white">Final Incident Report</h3>
                    <p className="text-xs text-[#A1A1AA]">Generated by CrisisOS AI</p>
                  </div>
                </div>
                <div className="flex gap-2">
                  <button className="px-3 py-1.5 bg-[#ffffff0a] hover:bg-[#ffffff14] border border-[#ffffff14] rounded text-sm text-white transition-colors flex items-center gap-2">
                    <i className="bx bx-copy"></i> Copy Text
                  </button>
                  <button className="px-3 py-1.5 bg-[#C871DA]/10 hover:bg-[#C871DA]/20 border border-[#C871DA]/30 rounded text-sm text-[#C871DA] transition-colors flex items-center gap-2">
                    <i className="bx bx-download"></i> Export PDF
                  </button>
                </div>
              </div>

              {/* Report Content */}
              <div className="p-8 flex-1 overflow-y-auto prose prose-invert max-w-none">
                <h1 className="text-3xl font-bold border-b border-[#ffffff14] pb-4 mb-6">Final Incident Report</h1>
                
                <div className="grid grid-cols-2 gap-4 mb-8 bg-[#ffffff05] p-6 rounded-xl border border-[#ffffff0a]">
                  <div><strong className="text-[#A1A1AA]">Incident ID:</strong> {incident.id}</div>
                  <div><strong className="text-[#A1A1AA]">Severity:</strong> {incident.severity}</div>
                  <div><strong className="text-[#A1A1AA]">Risk Score:</strong> {incident.riskScore}/100</div>
                  <div><strong className="text-[#A1A1AA]">Affected Service:</strong> {incident.affectedService}</div>
                  <div><strong className="text-[#A1A1AA]">Status:</strong> {incident.status}</div>
                  <div><strong className="text-[#A1A1AA]">Detected At:</strong> {new Date(incident.detectedAt).toLocaleString()}</div>
                </div>

                <h2 className="text-xl font-bold text-[#C871DA] mt-6 mb-3">Incident Summary</h2>
                <p className="text-[#F8FAFC]">{incident.description}</p>

                <h2 className="text-xl font-bold text-[#C871DA] mt-8 mb-3">Impact Assessment</h2>
                <p className="text-[#F8FAFC]">{incident.impact}</p>

                <h2 className="text-xl font-bold text-[#C871DA] mt-8 mb-3">Actions Taken</h2>
                <ul className="text-[#F8FAFC]">
                  <li>System detected anomaly and triggered AI Triage.</li>
                  <li>Incident assigned to {incident.assignedTo.join(', ')}.</li>
                  <li>Initial containment protocols initiated.</li>
                  <li>Evidence collected and stored in Vault.</li>
                </ul>

                <h2 className="text-xl font-bold text-[#22D3EE] mt-8 mb-3">Recommendations</h2>
                <ul className="text-[#F8FAFC]">
                  <li>Improve monitoring rules on {incident.affectedService}.</li>
                  <li>Review access control policies.</li>
                  <li>Configure stronger rate limiting.</li>
                  <li>Conduct formal post-incident review meeting.</li>
                </ul>
              </div>
            </div>
          ) : (
            <div className="card p-12 flex flex-col items-center justify-center text-[#71717A] h-full">
              <i className="bx bx-file text-6xl mb-4 opacity-50"></i>
              <p>Select an incident to view its report.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
